name: textlint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: '12.19.0'

      # Run scripts
      - name: Install dependencies
        run: yarn install
      - name: linting markdown files
        run: yarn run lint
